import { useCallback, useEffect, useMemo, useState } from 'react';
import { useCurrentAccount, useCurrentNetwork, useDAppKit } from '@mysten/dapp-kit-react';
import type { Transaction } from '@mysten/sui/transactions';
import { api } from '../api/client';
import { config } from '../config';
import type { AgentDescriptor, BountyResponse, ObjectId } from '../domain';

type Notice = { kind: 'success' | 'error' | 'info'; message: string } | null;
export interface TxReceipt { digest: string; events: Array<{ type?: string; parsedJson?: Record<string, unknown> }>; objectIds: ObjectId[]; }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'Unexpected request failure.'; }
function objectId(value: unknown): ObjectId | null { return typeof value === 'string' && /^0x[0-9a-f]{64}$/i.test(value) ? value.toLowerCase() as ObjectId : null; }

export function useDataBounty() {
  const account = useCurrentAccount(); const network = useCurrentNetwork(); const dAppKit = useDAppKit();
  const [data, setData] = useState<BountyResponse | null>(null); const [notice, setNotice] = useState<Notice>(null); const [busy, setBusy] = useState<string | null>(null); const [authenticatedAddress, setAuthenticatedAddress] = useState<string | null>(null); const [agents, setAgents] = useState<AgentDescriptor[]>([]);
  const sessionValid = account?.address === authenticatedAddress;
  const ready = useMemo(() => ({ wallet: !config.isPublicPreview && Boolean(account), network: !config.isPublicPreview && network === 'testnet', package: !config.isPublicPreview && Boolean(config.packageId), session: !config.isPublicPreview && sessionValid }), [account, network, sessionValid]);
  const previewError = () => new Error('This public preview is read-only. Run the local app for wallet and API actions.');
  const authenticate = useCallback(async () => { if (config.isPublicPreview) throw previewError(); if (!account) throw new Error('Connect a Sui wallet first.'); if (network !== 'testnet') throw new Error('Switch the wallet to Sui Testnet first.'); setBusy('auth'); try { const challenge = await api.challenge(account.address as `0x${string}`); const signed = await dAppKit.signPersonalMessage({ message: new TextEncoder().encode(challenge.message) }); const raw = signed as unknown as { signature?: string; serializedSignature?: string }; const signature = raw.signature ?? raw.serializedSignature; if (!signature) throw new Error('Wallet did not return a personal-message signature.'); const verified = await api.verify(challenge.challengeId, challenge.message, signature); setAuthenticatedAddress(verified.address); setNotice({ kind: 'success', message: 'Wallet signature verified for this browser session.' }); return verified.address; } catch (error) { setNotice({ kind: 'error', message: errorMessage(error) }); throw error; } finally { setBusy(null); } }, [account, dAppKit, network]);
  const loadBounty = useCallback(async (bountyId: ObjectId) => { if (config.isPublicPreview) throw previewError(); setBusy('load'); try { const next = await api.bounty(bountyId); setData(next); setNotice({ kind: 'success', message: `Loaded ${next.submissions.length} submission${next.submissions.length === 1 ? '' : 's'} from checkpoint ${next.bounty.checkpoint}.` }); return next; } catch (error) { setNotice({ kind: 'error', message: errorMessage(error) }); throw error; } finally { setBusy(null); } }, []);
  const execute = useCallback(async (label: string, transaction: Transaction): Promise<TxReceipt> => { if (config.isPublicPreview) throw previewError(); if (!account) throw new Error('Connect a Sui wallet first.'); if (network !== 'testnet') throw new Error('Switch the wallet to Sui Testnet before signing.'); if (!config.packageId) throw new Error('Set VITE_DATABOUNTY_PACKAGE_ID before signing.'); setBusy(label); try { const result = await dAppKit.signAndExecuteTransaction({ transaction }); const raw = result as unknown as { Transaction?: { digest?: string; events?: Array<{ type?: string; parsedJson?: Record<string, unknown> }> }; FailedTransaction?: { status?: { error?: { message?: string } } } }; if (raw.FailedTransaction) throw new Error(raw.FailedTransaction.status?.error?.message ?? 'Sui rejected the transaction.'); const txResult = raw.Transaction; const digest = txResult?.digest; if (!digest) throw new Error('Wallet returned no transaction digest.'); const events = txResult.events ?? []; const objectIds = events.flatMap((event) => Object.values(event.parsedJson ?? {}).map(objectId).filter((value): value is ObjectId => value !== null)); setNotice({ kind: 'success', message: `${label} confirmed · ${digest.slice(0, 12)}…` }); return { digest, events, objectIds }; } catch (error) { setNotice({ kind: 'error', message: errorMessage(error) }); throw error; } finally { setBusy(null); } }, [account, dAppKit, network]);
  const signPersonalMessage = useCallback(async (bytes: Uint8Array): Promise<string> => { if (config.isPublicPreview) throw previewError(); if (!account) throw new Error('Connect a Sui wallet first.'); const signed = await dAppKit.signPersonalMessage({ message: bytes }); const raw = signed as unknown as { signature?: string; serializedSignature?: string }; const signature = raw.signature ?? raw.serializedSignature; if (!signature) throw new Error('Wallet did not return a serialized signature.'); return signature; }, [account, dAppKit]);
  useEffect(() => { if (account?.address !== authenticatedAddress) setAuthenticatedAddress(null); }, [account?.address, authenticatedAddress]);
  useEffect(() => { if (config.isPublicPreview) return; void api.agents().then((response) => setAgents(response.agents)).catch(() => setAgents([])); }, []);
  const reviewerAddress = agents.find((agent) => agent.role === 'reviewer')?.delegateAddress ?? null;
  return { account, network, data, bounty: data?.bounty ?? null, submissions: data?.submissions ?? [], agents, reviewerAddress, notice, busy, ready, authenticate, loadBounty, execute, signPersonalMessage, setNotice, refresh: data ? () => loadBounty(data.bounty.id) : undefined };
}

/** Compatibility name for integrations that still import the old hook. */
export const useDraftProof = useDataBounty;
