import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { ConnectButton } from '@mysten/dapp-kit-react/ui';
import { api, ApiError, type Health } from './api/client';
import { config } from './config';
import { MAX_FILE_BYTES, MAX_PUBLIC_TASK_SPEC_BYTES, MAX_REVIEW_COMPARISONS, formatAddress, formatMist, normalizeObjectId, type Bounty, type ObjectId, type ReviewResponse, type SubmissionSummary } from './domain';
import { approveSubmissionAndPayTx, cancelOpenBountyTx, createBountyTx, finalizeSubmissionTx, grantReviewerTx, rejectSubmissionTx, refundExpiredBountyTx, reserveSubmissionTx, revokeReviewerTx } from './chain/transactions';
import { createCommitment, type SubmissionBundleV1 } from './crypto/commitment';
import { decryptBundle, encryptBundle, fetchCiphertext } from './crypto/seal';
import { clearRecovery, loadRecovery, saveRecovery } from './storage/recovery';
import { decodeBountyCreatedId, decodeSubmissionReservedId, useDataBounty } from './features/useDraftProof';
import { publicEvidence, pendingEvidence } from './publicEvidence';

type Prepared = { content: Uint8Array; filename: string; salt?: Uint8Array; commitment?: string };
const DEMO_SPEC = '한국어 피싱 문자 분류 학습용 사례 1건\n필수 필드: message, scam_type, red_flags, redacted_source_note';

function errorMessage(error: unknown): string { return error instanceof Error ? error.message : 'Unexpected failure. Check the reported chain state before retrying.'; }
function statusText(state: string): string { return ({ OPEN: 'Open', REVIEWING: 'Reviewing', PAID: 'Paid', EXPIRED_REFUNDED: 'Refunded', RESERVED: 'Reserved', READY: 'Ready', REJECTED: 'Rejected', ACCEPTED: 'Accepted', ABANDONED: 'Abandoned' } as Record<string, string>)[state] ?? state; }
function fileIsText(file: File): boolean { const ext = file.name.toLowerCase().split('.').pop(); return ext === 'txt' || ext === 'md'; }
function parseUtf8(file: File): Promise<Uint8Array> { return file.arrayBuffer().then((buffer) => { const bytes = new Uint8Array(buffer); if (bytes.length > MAX_FILE_BYTES) throw new Error('Cases must be 200 KiB or smaller.'); try { new TextDecoder('utf-8', { fatal: true }).decode(bytes); } catch { throw new Error('Cases must be valid UTF-8 .txt or .md files.'); } return bytes; }); }
function copyBuffer(bytes: Uint8Array): ArrayBuffer { const copy = new Uint8Array(bytes.byteLength); copy.set(bytes); return copy.buffer; }
function short(value: string | null | undefined, chars = 12): string { if (!value) return '—'; return value.length > chars ? `${value.slice(0, chars)}…` : value; }
const KST_TIME_ZONE = 'Asia/Seoul';
function formatKst(value: number | string): string { return new Intl.DateTimeFormat('ko-KR', { timeZone: KST_TIME_ZONE, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(Number(value))); }
function kstDateTimeInput(value: number): string { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: KST_TIME_ZONE, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(value)); const get = (type: string) => parts.find((part) => part.type === type)?.value ?? ''; return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`; }

export default function App() {
  const bounty = useDataBounty();
  const [bountyIdInput, setBountyIdInput] = useState('');
  const [taskSpec, setTaskSpec] = useState(DEMO_SPEC);
  const [rewardMist, setRewardMist] = useState('100000000');
  const [deadlineAt, setDeadlineAt] = useState(() => kstDateTimeInput(Date.now() + 24 * 60 * 60 * 1000));
  const [prepared, setPrepared] = useState<Prepared | null>(null);
  const [reservedSubmissionId, setReservedSubmissionId] = useState('');
  const [selectedId, setSelectedId] = useState<ObjectId | null>(null);
  const [reviewExpiry, setReviewExpiry] = useState(() => kstDateTimeInput(Date.now() + 60 * 60 * 1000));
  const [comparisonInput, setComparisonInput] = useState('');
  const [review, setReview] = useState<ReviewResponse | null>(null);
  const [reviewGrantConfirmedId, setReviewGrantConfirmedId] = useState<ObjectId | null>(null);
  const [opened, setOpened] = useState<{ submissionId: ObjectId; content: string } | null>(null);
  const [localError, setLocalError] = useState<string | null>(null);
  const [health, setHealth] = useState<Health | null>(null);
  const [publicTasks, setPublicTasks] = useState<Bounty[]>([]);
  const [boardError, setBoardError] = useState<string | null>(null);
  const [createdBountyId, setCreatedBountyId] = useState<string | null>(null);
  const [activePanel, setActivePanel] = useState<'create' | 'load' | 'authenticate' | 'contribute' | 'activity' | 'review' | 'guide' | null>(null);

  const selected = bounty.submissions.find((submission) => submission.id === selectedId) ?? null;
  const isRequester = Boolean(bounty.account && bounty.bounty && bounty.bounty.requester.toLowerCase() === bounty.account.address.toLowerCase());
  const isExpired = Boolean(bounty.bounty && BigInt(bounty.bounty.deadlineMs) <= BigInt(Date.now()));
  const chainReady = bounty.ready.wallet && bounty.ready.network && bounty.ready.package;
  const reviewReady = selected?.id === reviewGrantConfirmedId;

  useEffect(() => { if (config.isPublicPreview) return; void api.health().then(setHealth).catch(() => undefined); }, []);
  useEffect(() => { if (config.isPublicPreview) return; void api.bounties().then((response) => setPublicTasks(response.bounties)).catch(() => setBoardError('Public task board is temporarily unavailable.')); }, []);
  useEffect(() => {
    const styleWalletMenu = () => {
      const hosts: HTMLElement[] = [];
      const visit = (root: ParentNode) => {
        root.querySelectorAll<HTMLElement>('*').forEach((element) => {
          if (element.tagName === 'CONNECTED-ACCOUNT-MENU') hosts.push(element);
          if (element.shadowRoot) visit(element.shadowRoot);
        });
      };
      visit(document);
      hosts.forEach((host) => {
        const root = host.shadowRoot;
        if (!root || root.querySelector('[data-lighthouse-wallet-menu]')) return;
        const style = document.createElement('style');
        style.dataset.lighthouseWalletMenu = 'true';
        style.textContent = `:host { position: relative !important; } .menu { top: 0 !important; right: 0 !important; bottom: auto !important; left: auto !important; }`;
        root.append(style);
      });
    };
    styleWalletMenu();
    const observer = new MutationObserver(styleWalletMenu);
    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, []);
  function fail(error: unknown) { setLocalError(error instanceof ApiError ? `${error.code}: ${error.message}` : errorMessage(error)); }
  async function createBounty(event: FormEvent) { event.preventDefault(); setLocalError(null); try { if (!chainReady) throw new Error('Connect a Testnet wallet and configure VITE_DATABOUNTY_PACKAGE_ID first.'); if (new TextEncoder().encode(taskSpec).length > MAX_PUBLIC_TASK_SPEC_BYTES) throw new Error('The public task spec is too large.'); const receipt = await bounty.execute('Create and fund bounty', createBountyTx(taskSpec, String(new Date(deadlineAt).getTime()), rewardMist)); const id = decodeBountyCreatedId(receipt, config.packageId!); setBountyIdInput(id); setCreatedBountyId(id); if (bounty.ready.session) { await bounty.loadBounty(id); setActivePanel(null); } else setActivePanel('authenticate'); } catch (error) { fail(error); } }
  async function authenticateAndLoad() { setLocalError(null); try { await bounty.authenticate(); const id = createdBountyId ?? bountyIdInput; if (id) await bounty.loadBounty(normalizeObjectId(id)); setActivePanel(null); } catch (error) { fail(error); } }
  async function loadBounty(event: FormEvent) { event.preventDefault(); setLocalError(null); try { await bounty.loadBounty(normalizeObjectId(bountyIdInput)); } catch (error) { fail(error); } }
  async function openPublicTask(id: ObjectId) { setLocalError(null); setBountyIdInput(id); try { await bounty.loadBounty(id); setActivePanel('contribute'); } catch (error) { fail(error); } }
  async function chooseCase(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setLocalError(null); try { if (!fileIsText(file)) throw new Error('Choose a .txt or .md case.'); setPrepared({ content: await parseUtf8(file), filename: file.name }); setReservedSubmissionId(''); } catch (error) { fail(error); } }
  async function reserveCase() { if (!bounty.bounty || !prepared) return; setLocalError(null); try { const salt = crypto.getRandomValues(new Uint8Array(32)); const { contentCommitment } = await createCommitment(prepared.content, salt); setPrepared({ ...prepared, salt, commitment: contentCommitment }); const bountyId = bounty.bounty.id; const receipt = await bounty.execute('Reserve submission', reserveSubmissionTx(bountyId, contentCommitment)); setReservedSubmissionId(decodeSubmissionReservedId(receipt, config.packageId!)); await bounty.loadBounty(bountyId); } catch (error) { fail(error); } }
  async function encryptPublishFinalize() { if (!bounty.bounty || !prepared?.salt || !prepared.commitment) return; setLocalError(null); try { const submissionId = normalizeObjectId(reservedSubmissionId); const bundle: SubmissionBundleV1 = { formatVersion: 1, bountyId: bounty.bounty.id, submissionId, salt: prepared.salt, content: prepared.content }; const sealed = await encryptBundle(bounty.bounty.id, submissionId, bundle); await saveRecovery({ bountyId: bounty.bounty.id, submissionId, ciphertext: copyBuffer(sealed.ciphertext), ciphertextDigest: sealed.ciphertextDigest, stage: 'SEALED', updatedAt: new Date().toISOString() }); if (!bounty.ready.session) await bounty.authenticate(); const receipt = await api.publish(bounty.bounty.id, submissionId, sealed.ciphertext, sealed.ciphertextDigest); await saveRecovery({ bountyId: bounty.bounty.id, submissionId, ciphertext: copyBuffer(sealed.ciphertext), ciphertextDigest: receipt.ciphertextDigest, stage: 'PUBLISHED', blobId: receipt.blobId, storageEndEpoch: receipt.storageEndEpoch, updatedAt: new Date().toISOString() }); try { await bounty.execute('Finalize encrypted submission', finalizeSubmissionTx(bounty.bounty.id, submissionId, receipt.blobId, receipt.ciphertextDigest, receipt.storageEndEpoch)); } catch (error) { await saveRecovery({ bountyId: bounty.bounty.id, submissionId, ciphertext: copyBuffer(sealed.ciphertext), ciphertextDigest: receipt.ciphertextDigest, stage: 'FINALIZE_FAILED', blobId: receipt.blobId, storageEndEpoch: receipt.storageEndEpoch, updatedAt: new Date().toISOString() }); throw error; } await clearRecovery(bounty.bounty.id, submissionId); setPrepared(null); setReservedSubmissionId(''); await bounty.loadBounty(bounty.bounty.id); } catch (error) { fail(error); } }
  async function resumeSubmission(submission: SubmissionSummary) { if (!bounty.bounty) return; try { const record = await loadRecovery(bounty.bounty.id, submission.id); if (!record) throw new Error('No encrypted recovery record exists for this submission.'); const receipt = record.stage === 'SEALED' ? await api.publish(bounty.bounty.id, submission.id, new Uint8Array(record.ciphertext), record.ciphertextDigest) : { blobId: record.blobId!, ciphertextDigest: record.ciphertextDigest, storageEndEpoch: record.storageEndEpoch! }; await bounty.execute('Finalize recovered submission', finalizeSubmissionTx(bounty.bounty.id, submission.id, receipt.blobId, receipt.ciphertextDigest, receipt.storageEndEpoch)); await clearRecovery(bounty.bounty.id, submission.id); await bounty.loadBounty(bounty.bounty.id); } catch (error) { fail(error); } }
  async function openSubmission(submission: SubmissionSummary) { if (!bounty.bounty || !submission.blobId || !bounty.account) return; try { const ciphertext = await fetchCiphertext(submission.blobId); const digest = await crypto.subtle.digest('SHA-256', copyBuffer(ciphertext)); if (submission.ciphertextDigest && Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('') !== submission.ciphertextDigest) throw new Error('Walrus ciphertext digest differs from the onchain record.'); const bundle = await decryptBundle({ address: bounty.account.address, bountyId: bounty.bounty.id, submissionId: submission.id, ciphertext, signPersonalMessage: bounty.signPersonalMessage }); if (bundle.bountyId !== bounty.bounty.id || bundle.submissionId !== submission.id) throw new Error('Decrypted bundle IDs do not match the selected submission.'); const commitment = await createCommitment(bundle.content, bundle.salt); if (commitment.contentCommitment !== submission.contentCommitment) throw new Error('Decrypted content does not match its onchain commitment.'); setOpened({ submissionId: submission.id, content: new TextDecoder('utf-8', { fatal: true }).decode(bundle.content) }); } catch (error) { fail(error); } }
  async function grant(action: 'grant' | 'revoke') { if (!bounty.bounty || !selected) return; try { if (!bounty.reviewerAddress) throw new Error('The configured reviewer address is unavailable.'); const reviewer = bounty.reviewerAddress; if (action === 'grant') { const enteredExpiry = new Date(reviewExpiry).getTime(); const expiry = Number.isFinite(enteredExpiry) && enteredExpiry > Date.now() ? enteredExpiry : Date.now() + 60 * 60 * 1000; if (expiry !== enteredExpiry) setReviewExpiry(kstDateTimeInput(expiry)); await bounty.execute('Grant exact reviewer access', grantReviewerTx(bounty.bounty.id, selected.id, reviewer, String(expiry))); setReviewGrantConfirmedId(selected.id); } else { await bounty.execute('Revoke exact reviewer access', revokeReviewerTx(bounty.bounty.id, selected.id, reviewer)); setReviewGrantConfirmedId(null); } await bounty.loadBounty(bounty.bounty.id); } catch (error) { fail(error); } }
  async function runReview() { if (!bounty.bounty || !selected) return; try { const entered = comparisonInput.split(',').map((value) => value.trim()).filter(Boolean); const selectedComparisons = entered.length > 0 ? entered.map((value) => normalizeObjectId(value)) : []; if (selectedComparisons.length > MAX_REVIEW_COMPARISONS || new Set(selectedComparisons).size !== selectedComparisons.length || selectedComparisons.includes(selected.id)) throw new Error('Use up to five unique prior ACCEPTED Submission IDs and exclude the target.'); if (!bounty.ready.session) await bounty.authenticate(); const result = await api.review(bounty.bounty.id, { requestId: crypto.randomUUID(), submissionId: selected.id, comparisonSubmissionIds: selectedComparisons }); setReview(result); bounty.setNotice({ kind: 'success', message: `Grounded ${result.provider} review completed · ${result.model}` }); } catch (error) { fail(error); } }
  async function chainAction(label: string, tx: ReturnType<typeof rejectSubmissionTx>) { if (!bounty.bounty || !selected) return; try { await bounty.execute(label, tx); setReview(null); await bounty.loadBounty(bounty.bounty.id); } catch (error) { fail(error); } }

  if (config.isPublicPreview) return <PublicPreview />;
  const nextAction = !bounty.bounty ? { label: 'Create a Task', detail: 'Create a funded task or open a shared task ID.', action: 'create' as const } : isExpired ? { label: 'Task expired', detail: 'New contributions are closed. The requester can settle or refund according to chain state.', action: 'contribute' as const } : bounty.bounty.state === 'PAID' ? { label: 'Reward delivered', detail: 'Settlement is confirmed on Sui Testnet.', action: 'contribute' as const } : selected?.state === 'READY' && isRequester ? { label: 'Run AI review', detail: 'A sealed case is ready for grounded review.', action: 'review' as const } : selected?.state === 'RESERVED' ? { label: 'Encrypt contribution', detail: 'Encrypt, store, and finalize the reserved contribution.', action: 'contribute' as const } : { label: 'Open contribution route', detail: 'Invite a contributor or submit an encrypted case.', action: 'contribute' as const };
  return <main className="shell local-mode">
    <Header network={bounty.network} local role={bounty.account ? (isRequester ? 'Requester' : 'Contributor') : 'Explorer'} onGuide={() => setActivePanel('guide')} onActivity={bounty.account ? () => setActivePanel('activity') : undefined} />
    {activePanel === 'guide' ? <LighthouseGuide onBack={() => setActivePanel(null)} /> : <>
      <section className="minimal-deck">
        <div className="lighthouse-scene rendered-lighthouse" aria-hidden="true"><img src="/lighthouse-3d.png" alt="" /><span /></div>
        <div className="deck-copy"><p className="eyebrow">LIGHTHOUSE · DATABOUNTY</p><h1>{nextAction.label}</h1><p>{nextAction.detail}</p><div className="deck-actions"><button className="primary" onClick={() => setActivePanel(nextAction.action)}>{nextAction.action === 'create' ? 'Create Task' : nextAction.action === 'review' ? 'Open AI review' : 'Open route'} <span aria-hidden="true">↗</span></button>{!bounty.bounty && <button onClick={() => setActivePanel('load')}>Load shared task</button>}</div></div>
        <aside className="beacon-status"><span className="signal-dot" /> <div><small>TESTNET TASK</small><strong>{bounty.bounty ? `${statusText(bounty.bounty.state)} · ${formatMist(bounty.bounty.rewardMist)}` : 'No active task'}</strong></div></aside>
      </section>
      <section className="minimal-status" aria-label="Integration readiness"><span><i className={bounty.ready.wallet ? 'ready' : ''} />Wallet</span><span><i className={bounty.ready.network ? 'ready' : ''} />Testnet</span><span><i className={health?.status === 'ok' ? 'ready' : ''} />AI endpoint</span>{bounty.account && !bounty.ready.session && <button className="authenticate-cta" onClick={() => void authenticateAndLoad()} disabled={bounty.busy !== null}>Authenticate protected routes</button>}{bounty.bounty && <span><i className="ready" />Task {short(bounty.bounty.id, 10)}</span>}</section>
      {(bounty.notice || localError) && <div className={`notice ${localError || bounty.notice?.kind === 'error' ? 'notice-error' : 'notice-info'}`} role={localError || bounty.notice?.kind === 'error' ? 'alert' : 'status'}>{localError ?? bounty.notice?.message}</div>}
      {bounty.bounty && <section className="beacon-card"><div><p className="eyebrow">ACTIVE TASK</p><h2>{bounty.bounty.publicTaskSpec}</h2><p>{formatMist(bounty.bounty.rewardMist)} escrow · deadline {formatKst(bounty.bounty.deadlineMs)} KST</p></div><button onClick={() => setActivePanel('contribute')}>View cases</button></section>}
      {activePanel && <section className="action-sheet" aria-label="Lighthouse action sheet"><div className="sheet-top"><div><p className="eyebrow">{activePanel.toUpperCase()} ROUTE</p><h2>{activePanel === 'create' ? 'Create a new task' : activePanel === 'load' ? 'Open a shared task' : activePanel === 'authenticate' ? 'Authenticate this task' : activePanel === 'activity' ? 'My contribution status' : activePanel === 'contribute' ? 'Sealed Capsule route' : 'AI review and settlement'}</h2></div><button className="close-button" onClick={() => setActivePanel(null)}>Close</button></div>
        {activePanel === 'create' && <form onSubmit={createBounty} className="stack"><label>Public task spec<textarea value={taskSpec} onChange={(event) => setTaskSpec(event.target.value)} rows={4} /></label><div className="two-up"><label>Reward (MIST)<input inputMode="numeric" value={rewardMist} onChange={(event) => setRewardMist(event.target.value)} /></label><label>Deadline (KST)<input type="datetime-local" value={deadlineAt} onChange={(event) => setDeadlineAt(event.target.value)} /></label></div><button className="primary" disabled={!chainReady || bounty.busy !== null}>Create &amp; fund bounty <span aria-hidden="true">↗</span></button><ol className="auth-steps"><li><b>Fund the task.</b> Your Testnet SUI is placed in escrow.</li><li><b>Authenticate next.</b> Sign a personal message to unlock protected routes for this browser.</li><li><b>Load and share.</b> The task ID opens the contribution route.</li></ol></form>}
        {activePanel === 'load' && <form onSubmit={loadBounty} className="stack"><label>Bounty object ID<input value={bountyIdInput} onChange={(event) => setBountyIdInput(event.target.value)} placeholder="0x… 32-byte object ID" /></label><button className="primary" disabled={bounty.busy !== null}>Load shared bounty</button></form>}
        {activePanel === 'authenticate' && <section className="auth-sheet"><p>Your task was funded on Testnet. One personal-message signature is needed before Lighthouse can load private review routes for this browser.</p><code>{createdBountyId ?? bountyIdInput}</code><button className="primary auth-main-button" onClick={() => void authenticateAndLoad()} disabled={bounty.busy !== null}>Authenticate and open task</button><small>This is not a payment. It verifies the connected wallet for this browser session.</small></section>}
        {activePanel === 'activity' && <ContributionActivity bounty={bounty.bounty} submissions={bounty.submissions} account={bounty.account?.address ?? null} onOpen={(submission) => void openSubmission(submission)} />}
        {activePanel === 'contribute' && (!bounty.bounty ? <Empty title="No task loaded" text="Load or create a task before opening the sealed contribution route." /> : <>{isExpired && <p className="expired-notice">This Task deadline passed. New contributions are disabled.</p>}<div className="submission-list">{bounty.submissions.length === 0 ? <Empty title="No capsules yet" text="Choose a .txt or .md case to create the first encrypted capsule." /> : bounty.submissions.map((submission) => <button className={`submission-row ${selectedId === submission.id ? 'selected' : ''}`} key={submission.id} onClick={() => { setSelectedId(submission.id); setReview(null); }} aria-pressed={selectedId === submission.id}><span className={`state state-${submission.state.toLowerCase()}`} /><span><strong>{statusText(submission.state)} capsule</strong><small>{formatAddress(submission.contributor)} · {short(submission.id)}</small></span></button>)}</div>{selected && <SubmissionDetail submission={selected} isRequester={isRequester} reviewer={bounty.reviewerAddress} reviewExpiry={reviewExpiry} setReviewExpiry={setReviewExpiry} onGrant={() => void grant('grant')} onRevoke={() => void grant('revoke')} onOpen={() => void openSubmission(selected)} onResume={() => void resumeSubmission(selected)} onOpenReview={() => setActivePanel('review')} reviewReady={reviewReady} busy={bounty.busy !== null} />}{opened && <section className="opened"><div className="detail-title"><div><p className="eyebrow">FRESH SEAL READ</p><h3>{short(opened.submissionId, 20)}</h3></div><button onClick={() => setOpened(null)}>Clear plaintext</button></div><pre>{opened.content}</pre></section>}<SubmissionForm prepared={prepared} onFile={chooseCase} onReserve={() => void reserveCase()} onFinalize={() => void encryptPublishFinalize()} onDiscard={() => setPrepared(null)} reservedId={reservedSubmissionId} setReservedId={setReservedSubmissionId} busy={bounty.busy !== null} enabled={chainReady && !isExpired && bounty.bounty.state !== 'PAID' && bounty.bounty.state !== 'EXPIRED_REFUNDED'} />{isRequester && <div className="settlement-box compact-settlement"><span className="mini-label">HARBOR CONTROL</span><p>Cancel only an empty OPEN task, or refund after its deadline.</p><button onClick={() => void bounty.execute('Cancel open bounty', cancelOpenBountyTx(bounty.bounty!.id)).then(() => bounty.loadBounty(bounty.bounty!.id)).catch(fail)} disabled={bounty.busy !== null || bounty.bounty.readySubmissionCount > 0 || bounty.bounty.state === 'PAID' || bounty.bounty.state === 'EXPIRED_REFUNDED'}>Cancel empty task &amp; refund</button><button onClick={() => void bounty.execute('Refund expired bounty', refundExpiredBountyTx(bounty.bounty!.id)).then(() => bounty.loadBounty(bounty.bounty!.id)).catch(fail)} disabled={bounty.busy !== null || bounty.bounty.state === 'PAID' || bounty.bounty.state === 'EXPIRED_REFUNDED'}>Refund after deadline</button></div>}</>)}
        {activePanel === 'review' && (!bounty.bounty || !selected || selected.state !== 'READY' || !isRequester ? <Empty title="AI review is waiting for a READY capsule" text="Select a READY contribution as the requester before reviewing evidence." /> : <><div className="boundary-card"><span className="boundary-icon" aria-hidden="true">✦</span><div><strong>Recommendation ≠ settlement</strong><p>AI organizes evidence; the requester still signs the final payment.</p></div></div><label>Prior ACCEPTED IDs<input value={comparisonInput} onChange={(event) => setComparisonInput(event.target.value)} placeholder="0x… , 0x…" /></label><button className="primary full" onClick={() => void runReview()} disabled={bounty.busy !== null || !bounty.reviewerAddress || !reviewReady}>Run grounded AI review</button>{!reviewReady && <p className="hint">Grant exact read and wait for its Sui confirmation before running AI Review.</p>}{review && <><ReviewCard result={review} /><div className="action-row review-settlement"><button onClick={() => void chainAction('Reject submission', rejectSubmissionTx(bounty.bounty!.id, selected.id))} disabled={bounty.busy !== null}>Reject without payout</button><button className="primary" onClick={() => void chainAction('Approve and pay contributor', approveSubmissionAndPayTx(bounty.bounty!.id, selected.id))} disabled={bounty.busy !== null}>Approve &amp; pay contributor</button></div></>}</>)}
      </section>}
      <BountyBoard bounties={publicTasks} error={boardError} onOpen={(id) => void openPublicTask(id)} />
    </>}
  </main>;
}

function Header({ network, local = false, role, onGuide, onActivity }: { network?: string; local?: boolean; role?: string; onGuide?: () => void; onActivity?: () => void }) { const brand = <><img src="/lighthouse-mark.svg" alt="" aria-hidden="true" /><div><strong>Lighthouse</strong><small>by DataBounty</small></div></>; return <header className="topbar">{onGuide ? <button className="brand-lockup brand-home" onClick={onGuide} aria-label="Open Lighthouse introduction">{brand}</button> : <div className="brand-lockup">{brand}</div>}<div className="topbar-right">{onGuide && <button className="guide-link" onClick={onGuide}>About</button>}{onActivity && <button className="activity-link" onClick={onActivity}>My activity</button>}<span className={`mode-badge ${local ? 'local' : 'preview'}`}>{local ? 'LOCAL CONSOLE' : 'PUBLIC PREVIEW'}</span>{local ? <><span className="role-badge">{role}</span><div className="connection"><span>Sui {network || 'Testnet'}</span><ConnectButton /></div></> : <span className="preview-label">Wallet and network disconnected</span>}</div></header>; }
function ContributionActivity({ bounty, submissions, account, onOpen }: { bounty: Bounty | null; submissions: SubmissionSummary[]; account: string | null; onOpen(submission: SubmissionSummary): void }) { const mine = account ? submissions.filter((submission) => submission.contributor.toLowerCase() === account.toLowerCase()) : []; const detail = (submission: SubmissionSummary) => ({ RESERVED: 'Commitment recorded. Continue encryption and storage.', READY: 'Encrypted case is stored. Waiting for requester review and decision.', ACCEPTED: 'Reward was transferred automatically by the requester approval transaction.', REJECTED: 'Requester rejected this contribution. No payout was sent.', ABANDONED: 'This reserved contribution was abandoned.' } as Record<string, string>)[submission.state] ?? 'Waiting for an onchain update.'; return <section className="contribution-activity"><p className="eyebrow">MY ACTIVITY</p><h3>{bounty ? 'Current task contribution' : 'Open a task to see your contribution status'}</h3>{mine.length === 0 ? <p className="hint">No contribution from this wallet is visible in the current task yet. Open a public task, submit a case, then return here to track it.</p> : <div className="activity-list">{mine.map((submission) => <article key={submission.id}><span className={`task-state ${submission.state.toLowerCase()}`}>{statusText(submission.state)}</span><div><strong>{short(submission.id, 18)}</strong><p>{detail(submission)}</p>{submission.blobId && <small>Walrus blob {short(submission.blobId, 18)}</small>}</div>{submission.state === 'READY' || submission.state === 'ACCEPTED' ? <button onClick={() => onOpen(submission)}>Inspect status</button> : null}</article>)}</div>}<div className="payout-note"><strong>Reward status</strong><p>This contract transfers the reward automatically when the requester approves. A separate claim action does not exist in the current Testnet Move contract.</p></div></section>; }
function BountyBoard({ bounties, error, onOpen }: { bounties: Bounty[]; error: string | null; onOpen(id: ObjectId): void }) { return <section className="bounty-board" aria-label="Public task board"><div className="board-heading"><div><p className="eyebrow">PUBLIC TASK BOARD</p><h2>Open contribution requests</h2></div><span>{bounties.length} live</span></div>{error ? <p className="hint">{error}</p> : bounties.length === 0 ? <p className="hint">No public tasks found yet.</p> : <div className="task-grid">{bounties.map((task) => <article className="task-card" key={task.id}><div><span className={`task-state ${task.state.toLowerCase()}`}>{statusText(task.state)}</span><h3>{task.publicTaskSpec}</h3><p>{formatMist(task.rewardMist)} · closes {formatKst(task.deadlineMs)} KST</p></div><button onClick={() => onOpen(task.id)}>Open task</button></article>)}</div>}</section>; }
function LighthouseGuide({ onBack }: { onBack(): void }) { return <section className="lighthouse-guide"><div className="guide-scene rendered-lighthouse hero-lighthouse" aria-hidden="true"><img src="/lighthouse-hero-cutout.png" alt="" /><span /></div><p className="eyebrow">LIGHTHOUSE BY DATABOUNTY</p><h1>Send a signal.<br /><em>Bring rare data home.</em></h1><p className="guide-copy">빛을 보내면, 희소 데이터가 안전한 경로로 돌아옵니다. Lighthouse turns one scarce AI case into a verifiable, protected, and rewarded contribution route.</p><p className="guide-line">From signal to proof to reward.</p><div className="guide-steps"><span><b>01</b> Task<br /><small>Sui escrow</small></span><span><b>02</b> Sealed Capsule<br /><small>Encrypted contribution</small></span><span><b>03</b> AI Review<br /><small>Grounded AI evidence</small></span><span><b>04</b> Light Delivered<br /><small>Human-approved reward</small></span></div><section className="architecture-explainer" aria-label="How Lighthouse works"><div className="architecture-heading"><p className="eyebrow">ONE ROUTE, FOUR ROLES</p><h2>AI checks the evidence. The owner still controls the outcome.</h2></div><div className="architecture-flow"><span>Task</span><i>→</i><span>Encrypted case</span><i>→</i><span>Evidence</span><i>→</i><span>Reward</span></div><div className="role-cards"><article><span className="role-icon">SUI</span><h3>Escrow &amp; ownership</h3><p>요청자가 보상을 예치하고, 승인·지급의 최종 권한을 직접 가진다.</p></article><article><span className="role-icon walrus">WALRUS</span><h3>Deep Storage</h3><p>암호화된 사례를 저장하고, 원문을 바꾸지 않은 채 다시 읽을 수 있게 한다.</p></article><article><span className="role-icon seal">SEAL</span><h3>Protected route</h3><p>검토자에게도 특정 사례·정해진 시간만 읽을 수 있는 권한을 부여한다.</p></article><article><span className="role-icon ai">AI</span><h3>Grounded AI Review</h3><p>필수 필드, 인용 근거, 중복 후보를 검사한다. AI는 보상을 보내지 않는다.</p></article></div><p className="human-gate"><b>Human gate:</b> AI의 추천은 증거일 뿐입니다. 지급은 요청자가 Sui 지갑으로 최종 승인해야만 실행됩니다.</p></section><button className="primary open-workspace" onClick={onBack}>Open workspace <span aria-hidden="true">↗</span></button></section>; }
function PublicPreview() { return <main className="shell preview-mode"><Header /><section className="hero preview-hero"><div><p className="eyebrow">PUBLIC READ-ONLY EVIDENCE LEDGER · DATABOUNTY PROTOCOL</p><h1>A calmer way to trace <em>contribution.</em></h1><p className="hero-copy">Lighthouse is the public window into DataBounty: encrypted cases, grounded AI evidence, and human approved settlement on Sui Testnet.</p><div className="preview-callout" role="status"><strong>Static preview</strong><span>Wallet, API, upload, AI review, payout, refund, and cancel controls are intentionally disconnected.</span></div></div><div className="hero-signal"><span className="signal-dot" /> Evidence ledger <strong>Recorded package + escrow</strong></div></section><section className="preview-layout"><section className="panel preview-story"><p className="eyebrow">WHY LIGHTHOUSE</p><h2>See the boundary between evidence and action.</h2><p>DataBounty keeps the encrypted contribution path inspectable while Lighthouse gives teams a compact operational view. AI can recommend; only the requester can settle a bounty with a wallet signature.</p><div className="preview-steps"><span><b>01</b> Public task + escrow</span><span><b>02</b> Encrypted case trail</span><span><b>03</b> Grounded review card</span><span><b>04</b> Human settlement</span></div><nav className="preview-links" aria-label="Project links"><a href="https://suiscan.xyz/testnet/object/0xf7923bd34625af96c40e27187371f231fca6bca7d25d244fe72244ec9a89b0aa" target="_blank" rel="noreferrer">Sui Testnet package ↗</a><a href="https://github.com/diveyreadytodive-star/DataBounty" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://app.notion.com/p/3db43a5370a681448a43f05a8ffa2338?pvs=204" target="_blank" rel="noreferrer">Project notes ↗</a></nav></section><section className="panel ledger"><div className="panel-heading"><div><p className="eyebrow">RECORDED EVIDENCE</p><h2>Evidence ledger</h2><p>Public identifiers and dated limits, without secrets or plaintext.</p></div></div><div className="ledger-list">{publicEvidence.map((item) => <article className="ledger-row" key={item.id}><span className={`ledger-status ${item.status}`}>{item.status === 'verified' ? 'VERIFIED' : 'RECORDED'}</span><div><strong>{item.label}</strong><p>{item.detail}</p><code>{item.identifier}</code></div><time>{item.date}</time></article>)}</div><div className="pending-box"><span className="mini-label">EXPLICITLY PENDING</span>{pendingEvidence.map((item) => <span key={item}>{item}</span>)}</div></section></section><section className="preview-boundary"><span className="boundary-icon" aria-hidden="true">✦</span><div><strong>Read-only by design</strong><p>This public build makes no wallet, API, upload, review, or payout calls. Run the local Lighthouse console with explicit Testnet configuration to operate the protocol.</p></div></section></main>; }

function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><span className="empty-mark" aria-hidden="true">⌁</span><h3>{title}</h3><p>{text}</p></div>; }
function SubmissionForm({ prepared, onFile, onReserve, onFinalize, onDiscard, reservedId, setReservedId, busy, enabled }: { prepared: Prepared | null; onFile(event: ChangeEvent<HTMLInputElement>): void; onReserve(): void; onFinalize(): void; onDiscard(): void; reservedId: string; setReservedId(value: string): void; busy: boolean; enabled: boolean }) { return <section className="contributor"><div className="section-title"><div><p className="eyebrow">CONTRIBUTOR LANE</p><h3>Contribute an encrypted case</h3></div><span className="pill">2 steps</span></div>{!prepared ? <><label className="file-picker">Choose .txt or .md<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={onFile} /></label><p className="hint">UTF-8 text up to 200 KiB. Filename, salt, and plaintext never enter chain state or IndexedDB.</p></> : <><p className="prepared"><strong>{prepared.filename}</strong> · {prepared.content.byteLength.toLocaleString()} bytes</p><div className="contribution-steps"><div><span>1</span><button className="primary" onClick={onReserve} disabled={!enabled || busy || Boolean(prepared.commitment)}>Reserve Submission</button><small>Commit bytes, then read the exact onchain ID.</small></div><div><span>2</span><label>Reserved Submission ID<input value={reservedId} onChange={(event) => setReservedId(event.target.value)} placeholder="0x…" /></label><button className="primary" onClick={onFinalize} disabled={!enabled || busy || !prepared.commitment}>Encrypt, publish, finalize</button></div></div><button className="text-button" onClick={onDiscard} disabled={busy}>Discard plaintext</button></>}</section>; }
function SubmissionDetail({ submission, isRequester, reviewer, reviewExpiry, setReviewExpiry, onGrant, onRevoke, onOpen, onResume, onOpenReview, reviewReady, busy }: { submission: SubmissionSummary; isRequester: boolean; reviewer: string | null; reviewExpiry: string; setReviewExpiry(value: string): void; onGrant(): void; onRevoke(): void; onOpen(): void; onResume(): void; onOpenReview(): void; reviewReady: boolean; busy: boolean }) {
  return <section className="detail"><div className="detail-title"><div><p className="eyebrow">SELECTED SUBMISSION</p><h3>{statusText(submission.state)}</h3></div><code title={submission.id}>{submission.id}</code></div><dl><div><dt>Contributor</dt><dd>{submission.contributor}</dd></div><div><dt>Commitment</dt><dd>{submission.contentCommitment}</dd></div><div><dt>Walrus blob</dt><dd>{submission.blobId ?? 'Not finalized'}</dd></div><div><dt>Storage end epoch</dt><dd>{submission.storageEndEpoch ?? '—'}</dd></div></dl>{submission.state === 'RESERVED' && <div className="action-row"><button onClick={onResume} disabled={busy}>Resume encrypted upload</button></div>}{(submission.state === 'READY' || submission.state === 'ACCEPTED') && <div className="grant-box"><button className="primary" onClick={onOpen} disabled={busy}>Request fresh key &amp; open</button>{isRequester && <><h4>Reviewer access</h4><label>Configured reviewer wallet<input value={reviewer ?? ''} readOnly placeholder="Configure REVIEWER_DELEGATE_ADDRESS" /></label><label>Expires at (KST)<input type="datetime-local" value={reviewExpiry} onChange={(event) => setReviewExpiry(event.target.value)} /></label><div className="action-row"><button onClick={onGrant} disabled={busy || !reviewer}>Grant exact read</button><button onClick={onRevoke} disabled={busy || !reviewer}>Revoke read</button></div>{submission.state === 'READY' && <><button className="primary full" onClick={onOpenReview} disabled={busy || !reviewReady}>Continue to AI review</button>{!reviewReady && <p className="hint">Grant exact read first. AI Review remains locked until the Sui grant is confirmed.</p>}</>}</>}</div>}</section>;
}
function ReviewCard({ result }: { result: ReviewResponse }) {
  const decision = {
    RECOMMEND_ACCEPT: { label: '승인 권고', description: '요청자가 지정한 필수 항목이 제출 원문에서 확인되었습니다.', tone: 'accept' },
    RECOMMEND_REJECT: { label: '거절 권고', description: '요청자가 지정한 기준을 충족하지 못한 항목이 있습니다.', tone: 'reject' },
    NEEDS_HUMAN_REVIEW: { label: '사람 검토 필요', description: 'AI만으로는 요청자의 기준 충족 여부를 확정할 수 없습니다.', tone: 'review' },
  }[result.recommendation];
  const checks = [...result.checklist].sort((left, right) => left.field.localeCompare(right.field));
  const status = { PRESENT: '확인됨', MISSING: '누락', UNCLEAR: '판단 보류' } as const;
  const cited = (ids: number[]) => ids.length ? ids.map((id) => `근거 #${id + 1}`).join(', ') : '연결된 근거 없음';
  const presentCount = checks.filter((item) => item.status === 'PRESENT').length;

  return <article className="ai-result" aria-label="AI review report">
    <header className="review-report-header">
      <div><p className="eyebrow">AI REVIEW REPORT</p><h3>{decision.label}</h3></div>
      <span className={`review-decision ${decision.tone}`}>{result.recommendation.replace('RECOMMEND_', '').replaceAll('_', ' ')}</span>
    </header>
    <section className="review-summary">
      <strong>판정 요약</strong>
      <p>{decision.description} 필수 항목 {presentCount}/{checks.length}개가 확인되었습니다.</p>
    </section>
    <section className="review-section">
      <div className="review-section-heading"><h4>1. 필수 항목 검증</h4><span>{checks.length}개 항목</span></div>
      <div className="review-check-list">{checks.map((item) => <article className={`review-check ${item.status.toLowerCase()}`} key={item.field}><div><strong>{item.field}</strong><small>{cited(item.citationIds)}</small></div><span>{status[item.status]}</span></article>)}</div>
    </section>
    <section className="review-section">
      <div className="review-section-heading"><h4>2. 중복 검사</h4><span>{result.duplicateCandidates.length ? `${result.duplicateCandidates.length}개 비교` : '비교 자료 없음'}</span></div>
      {result.duplicateCandidates.length === 0 ? <p className="review-empty">비교 대상으로 지정된 기존 승인 사례가 없습니다.</p> : <div className="review-check-list">{result.duplicateCandidates.map((candidate) => <article className={`review-check ${candidate.verdict === 'POSSIBLE' ? 'unclear' : 'present'}`} key={candidate.submissionId}><div><strong>{short(candidate.submissionId)}</strong><small>{cited(candidate.citationIds)}</small></div><span>{candidate.verdict === 'POSSIBLE' ? '유사 가능성' : '중복 없음'}</span></article>)}</div>}
    </section>
    <details className="review-evidence"><summary>3. 원문 근거 {result.citations.length}개 보기</summary><div>{result.citations.map((citation, index) => <article key={`${citation.submissionId}-${citation.startByte}`}><header><strong>근거 #{index + 1}</strong><small>UTF-8 bytes {citation.startByte}–{citation.endByte}</small></header><blockquote>{citation.quote}</blockquote></article>)}</div></details>
    <footer className="review-provenance"><span>{result.provider} · {result.model}</span><span>AI 권고는 지급이 아닙니다. 원문 근거를 확인한 뒤 요청자가 최종 승인합니다.</span></footer>
  </article>;
}
