import type { ObjectId } from '../domain';
export type UploadStage = 'SEALED' | 'PUBLISHED' | 'FINALIZE_FAILED';
export interface RecoveryRecord { bountyId: ObjectId; submissionId: ObjectId; ciphertext: ArrayBuffer; ciphertextDigest: string; stage: UploadStage; blobId?: string; storageEndEpoch?: string; updatedAt: string; }
const DB_NAME = 'databounty-recovery-v1'; const STORE = 'encrypted-submissions';
function key(record: Pick<RecoveryRecord, 'bountyId' | 'submissionId'>): string { return `${record.bountyId}:${record.submissionId}`; }
function database(): Promise<IDBDatabase> { return new Promise((resolve, reject) => { const open = indexedDB.open(DB_NAME, 1); open.onupgradeneeded = () => open.result.createObjectStore(STORE, { keyPath: 'recoveryKey' }); open.onsuccess = () => resolve(open.result); open.onerror = () => reject(open.error); }); }
export async function saveRecovery(record: RecoveryRecord): Promise<void> { const db = await database(); await new Promise<void>((resolve, reject) => { const tx = db.transaction(STORE, 'readwrite'); tx.objectStore(STORE).put({ ...record, recoveryKey: key(record) }); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); }); db.close(); }
export async function loadRecovery(bountyId: ObjectId, submissionId: ObjectId): Promise<RecoveryRecord | null> { const db = await database(); const record = await new Promise<RecoveryRecord | null>((resolve, reject) => { const req = db.transaction(STORE).objectStore(STORE).get(key({ bountyId, submissionId })); req.onsuccess = () => resolve((req.result as RecoveryRecord | undefined) ?? null); req.onerror = () => reject(req.error); }); db.close(); return record; }
export async function clearRecovery(bountyId: ObjectId, submissionId: ObjectId): Promise<void> { const db = await database(); await new Promise<void>((resolve, reject) => { const req = db.transaction(STORE, 'readwrite').objectStore(STORE).delete(key({ bountyId, submissionId })); req.onsuccess = () => resolve(); req.onerror = () => reject(req.error); }); db.close(); }
